version: '3.7'
services:
  mysql:
    container_name: usr-mysql
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_SID
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - "${DB_PORT}:3306"
  redis:
    container_name: usr-redis
    image: redis
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${REDIS_PORT}:6379"